# -*- coding: utf-8 -*-
"""pythonbasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVeOpE3kOTvN2uGWIHEP5OzPybNt0ghf
"""

my_int = 22
print("Original integer:", my_int)

my_list = [1, "hiii", 30.12,3.9, True]
print("Original list:", my_list)
my_list.append('word')
print("List after appending 'word':",my_list)
my_list.remove(30.12)
print("List after removing 30.12:", my_list)

tuple1 = (1, 'apple', 30.12, False)
print("Original tuple:", tuple1)
print("First element:",tuple1[0])
print("Second element:", tuple1[1])
print("Last element:", tuple1[-1])

for i in range(1,5):
  print(i)

i = 1
while i <= 5:
  print(i)
  i += 1

number = int(input("Enter a number:"))
if number > 0:
  print("The number is positive.")
elif number < 0:
  print("The number is negative.")
else:
  print("The number is zero.")

def greet(name):
  print(f"Heyyy!!!! from function, {name}!")
greet("John")

print(dir(str))
#all built in functions

a='hello WoRld, HII!!'
b= a.upper()
c= a.swapcase()
d= a.lower()
print(c)
print(d)
print(b)

a= 'hello world'
b= a.replace('hello', 'HII')
print(b)

str1='123a'
str2='069'
result = str1.isdigit()
print(result)
result = str2.isdigit()
print(result)

a =range(10)
print(a)

a = range(9)
b=list(a)
print(b)

my_list = list(range(1,11,3))
print(my_list)

def add_numbers(a,b):
  return a+b
result = add_numbers(5,3)
print(result)

# function with returns
def add_numbers(a,b):
  result = a+b
  return result
print(add_numbers(22,7))

# function with default
def greet(name, greeting='hello'):
    print(f"{greeting}, {name}!")

# function with *arg - n number of arguments, nothing to be predefined
def calc_sum(*args):
  total = sum(args)
  return total
print("sum of 1,2,3:", calc_sum(1,2,3))
print("sum of 1,2,3,4:", calc_sum(1,2,3,4))

# creating a program and adding 2 or more features to it
# predefined correct username and password
correct_username = "asad"
correct_password = "007"
#prompt the user to get input
while True:
  username = input("Enter your username:")
  password = input("Enter your password:")
  if username ==correct_username and password == correct_password:
        print("Login successful!")
        break
  else:
    print("Invalid username or password, please try again")

#removesuffix
#removeprefix
a ='hello world!!, hii james'
b= a.removeprefix('hello')
print(b)
c ='hello world'
d= c.removesuffix('hii')
print(d)

print(dir(str))

